spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Currency
    username: postgres
    password: Fateavernous123
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: authentication-service

logging:
  level:
    com.example.authentication: INFO
    org.hibernate: INFO
    liquibase: INFO

server:
  error:
    include-message: always
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
