spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Currency
    username: postgres
    password: Fateavernous123
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
  port: 8080