spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    liquibase-schema: currency
    default-schema: currency
  datasource:
    url: jdbc:postgresql://localhost:5432/Currency
    username: postgres
    password: 
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: currency-rate-service

logging:
  level:
    com.example.currencyexchange: INFO
    org.hibernate: INFO
    liquibase: INFO
  file.path: D:/logs
  file.name: ${logging.file.path}/currency.log

server:
  error:
    include-message: always
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
