spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Currency
    username: postgres
    password:
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: currency-calculation-service

server:
  error:
    include-message: always
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka