spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Currency
    username: postgres
    password: Fateavernous123
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: currency_exchange
#          uri: 'http://localhost:8000'
          uri: lb://CURRENCY-RATE-SERVICE
          predicates:
            - Path=/api/v1/exchange/**
#            - Query=src,exchange
        - id: calculate
#          uri: 'http://localhost:9000'
          uri: lb://CURRENCY-CALCULATION-SERVICE
          predicates:
            - Path=/api/v1/calculate/**
#            - Query=src,calculate

server:
  error:
    include-message: always
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka